name: bootstrap-v4
recipe: lamp
config:
  webroot: _site

services:
  node:
    type: node:18
#    build:
#      - npm ci
    build_as_root:
      - apt-get update -y
      - apt-get install -y chromium --no-install-recommends
      - apt-get clean && rm -rf /var/lib/apt/lists/*

tooling:
  node:
    service: node
  npm:
    service: node
  npx:
    service: node
